AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  watts-going-on

  SAM Template for watts-going-on

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - production
      - staging
    Description: Parameter for getting the deployment environment. Override on the command-line to deploy to production.
  DDParamName:
    Type: String
    Default: DDApiKey
    Description: Name of the parameter in AWS Systems Manager Parameter Store storing the Datadog API key.

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        DD_SITE: datadoghq.com
        ENV: !Ref Environment
        SERVICE: watts-ifttt
        SOURCE: watts
        VERSION: 1.0.0

Resources:
  WattsSendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: watts/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        WattsSend:
          Type: Api
          Properties:
            Path: /send
            Method: post
      Environment:
        Variables:
          DD_API_KEY_NAME: !Ref DDParamName
      Policies:
        - Statement:
            - Sid: GetDDParamPolicy
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Join ['/', [!Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter', !Ref DDParamName]]

Outputs:
  WattsSendApi:
    Description: "API Gateway endpoint URL for Prod stage for Watts Send function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send/"
  WattsSendFunction:
    Description: "Watts Send Lambda Function ARN"
    Value: !GetAtt WattsSendFunction.Arn
  WattsSendFunctionIamRole:
    Description: "Implicit IAM Role created for Watts Send function"
    Value: !GetAtt WattsSendFunctionRole.Arn
